# This is the Container for the MariaDB Database
#
# We need to do the following:
	# 1. Create a Docker Container from base image debian:bullseye
	# 2. Install the required packages
	#		- mariadb-server
	#		- iputils-ping (to be able to ping the container)
	# 3. Remove the apt cache
	# 4. Copy the configuration files
	#		- setup_db.sh 	(which is the script to setup the database)
	#		- setup_db.sql	(which is the sql script to create the database)













FROM debian:bullseye

# Steps 1 - 3
RUN apt update &&  \
	apt install -y mariadb-server iputils-ping && \
	rm -rf /var/lib/apt/lists/*

# Copy the configuration files
COPY setup_db.sh	/etc/mysql/setup_db.sh
COPY setup_db.sql	/etc/mysql/setup_db.sql
#COPY 50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf

# Set the permissions
RUN mkdir -p /run/mysqld && chmod +x /etc/mysql/setup_db.sh 

RUN chown -R mysql:mysql /var/lib/mysql /var/log/mysql

# Expose the port
EXPOSE 3306

# Setup the database
ENTRYPOINT [ "/etc/mysql/setup_db.sh" ]