FROM debian:bullseye

# Install mariadb-server and mariadb-client
RUN apt update && \
    apt install -y mariadb-server mariadb-client mariadb-common && \
    rm -rf /var/lib/apt/lists/*

# Create the directory for maraidb.sock and change the owner to mysql
RUN mkdir -p /run/mysqld && \
	chown -R mysql:mysql /run/mysqld

# Copy the setup script and make it executable
COPY ./tools/setup_db.sh .
RUN chmod +x setup_db.sh

# Expose the port
EXPOSE 3306

# Setup the database and start the database server
ENTRYPOINT ./setup_db.sh
