FROM debian:bullseye

# Steps 1 - 3
RUN apt update && \
    apt install -y mariadb-server && \
    rm -rf /var/lib/apt/lists/*

# Copy the configuration files and set the permissions

RUN mkdir /var/run/mysqld && \
chmod 777 /var/run/mysqld && \
sed -i 's/^bind-address/#bind-address/' /etc/mysql/mariadb.conf.d/50-server.cnf

RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY setup_db.sh /etc/mysql/setup_db.sh
RUN chmod +x /etc/mysql/setup_db.sh

USER mysql

RUN	bash /etc/mysql/setup_db.sh

# Expose the port
EXPOSE 3306

# Setup the database and start the database server
# ENTRYPOINT [ "/etc/mysql/setup_db.sh" ]

CMD ["/usr/sbin/mysqld", "--skip-log-error"]
