FROM debian:bullseye

RUN apt update && apt install -y mariadb-server

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN mkdir -p /run/mysqld
COPY init.sql /etc/mysql/init.sql

CMD [ "mysqld" ]