FROM debian:bullseye

RUN apt update && apt install -y mariadb-server

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY init.sql /etc/mysql/init.sql
COPY start_db.sh .

RUN mkdir -p /run/mysqld && chmod +x start_db.sh

CMD [ "./start_db.sh" ]