FROM debian:bullseye

# Install
#	-	PHP
#	-	the php package for MariaDB (mysqli - the i stands for improved)
#	-	curl to download wordpress
RUN apt update && apt install -y \
	php-fpm \
	php-mysqli \
	curl \
	iputils-ping

RUN mkdir -p /run/php
COPY www.conf /etc/php/7.4/fpm/pool.d/www.conf

# Copy the install script
COPY install_wp.sh .
RUN chmod +x install_wp.sh

CMD ["./install_wp.sh"]
