FROM debian:bullseye

RUN echo updating and installing php-fpm
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y php-fpm
RUN echo DONE> updating and installing php-fpm

COPY www.conf /etc/php/7.4/fpm/pool.d/www.conf

CMD ["sleep", "1000000"]
#CMD ["php-fpm7.4", "-F"]
